# Generated by Django 3.1.4 on 2020-12-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_created=True, null=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('img', models.ImageField(upload_to='project/')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
